// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Infrastructure.SQLite.Context;

#nullable disable

namespace Movies.Infrastructure.SQLite.Migrations
{
    [DbContext(typeof(MoviesDbContext))]
    [Migration("20241214163904_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Movies.Domain.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur10")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur11")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur12")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur13")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur14")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur15")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur16")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur6")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur7")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur8")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acteur9")
                        .HasColumnType("TEXT");

                    b.Property<int>("Annee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssistantRealisateur1")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssistantRealisateur2")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssistantRealisateur3")
                        .HasColumnType("TEXT");

                    b.Property<int>("Complet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DApres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dervision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dialogue")
                        .HasColumnType("TEXT");

                    b.Property<int>("Minutage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Montage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Musique")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ou")
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Qui")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Realisateur1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Realisateur2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scenario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scenario1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitreOriginal")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerificationCD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
